// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_adapt = "CgkIm6CK7OEHEAIQBg"; // <GPGSID>
        public const string leaderboard_word = "CgkIm6CK7OEHEAIQEA"; // <GPGSID>
        public const string achievement_genious = "CgkIm6CK7OEHEAIQBA"; // <GPGSID>
        public const string achievement_its_something = "CgkIm6CK7OEHEAIQFA"; // <GPGSID>
        public const string achievement_mastermind = "CgkIm6CK7OEHEAIQFQ"; // <GPGSID>
        public const string achievement_clever = "CgkIm6CK7OEHEAIQAw"; // <GPGSID>
        public const string achievement_improvise = "CgkIm6CK7OEHEAIQBQ"; // <GPGSID>
        public const string achievement_sparkle = "CgkIm6CK7OEHEAIQAg"; // <GPGSID>
        public const string achievement_barry_allen = "CgkIm6CK7OEHEAIQDg"; // <GPGSID>
        public const string achievement_color_palette = "CgkIm6CK7OEHEAIQEw"; // <GPGSID>
        public const string leaderboard_tapping = "CgkIm6CK7OEHEAIQDA"; // <GPGSID>
        public const string achievement_tried_in_keyboard = "CgkIm6CK7OEHEAIQCw"; // <GPGSID>
        public const string achievement_one_finger_man = "CgkIm6CK7OEHEAIQCQ"; // <GPGSID>
        public const string achievement_average_human = "CgkIm6CK7OEHEAIQDQ"; // <GPGSID>
        public const string leaderboard_intelligence = "CgkIm6CK7OEHEAIQAQ"; // <GPGSID>
        public const string leaderboard_typing = "CgkIm6CK7OEHEAIQCA"; // <GPGSID>
        public const string achievement_overcome = "CgkIm6CK7OEHEAIQBw"; // <GPGSID>
        public const string achievement_i_am_colorblind = "CgkIm6CK7OEHEAIQEg"; // <GPGSID>
        public const string achievement_savitar = "CgkIm6CK7OEHEAIQDw"; // <GPGSID>
        public const string achievement_2_fast_fingers = "CgkIm6CK7OEHEAIQCg"; // <GPGSID>
        public const string leaderboard_visual = "CgkIm6CK7OEHEAIQEQ"; // <GPGSID>

}

